# Test settings for pywerMeter
# Test timers are in minutes!!!! Delay is in seconds Decimals are allowed.
# Test filenames should end with .csv
test_settings:
  # Off
  test_filename_1: "1_off.txt"
  test_duration_1: 1
  after_test_pause_1: true
  # Short Idle
  test_filename_2: "2_short_idle.txt"
  test_duration_2: 2 # in minutes
  test_pre_delay_2: 3 # in seconds
  after_test_pause_2: false
  # Long Idle
  test_filename_3: "3_long_idle.txt"
  test_duration_3: 3 # in minutes
  test_pre_delay_3: 0 # in seconds
  after_test_pause_3: false
  # Sleep
  test_filename_4: "4_sleep.txt"
  test_duration_4: 4 # in minutes
  test_pre_delay_4: 0 # in seconds
  after_test_pause_4: false

# Serial Command Settings
command_setttings:
  command: b'?MPOW'

# Serial Connection Settings Configuartion
connection_settings:
  port: "COM7" 
  baudrate: 38400
  bytesize: 8
  stopbits: 1
  timeout: 1

# Logging Settings
log_settings:
  log_dir: "./logs"
  log_level: "DEBUG"