# Serial Connection Settings Configuartion
connection_settings:
  port: "COM7" 
  baudrate: 9600
  bytesize: serial.EIGHTBITS
  stopbits: serial.STOPBITS_ONE
  timeout: 1

# Serial Command Settings
command_setttings:
  command: b'?MPOW'
  timeout: 0.5

# Logging Settings
log_settings:
  log_dir: "./logs"
  log_level: "DEBUG"